name: Handle Notification Dispatch

on:
  repository_dispatch:
    types: [send-notification]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run Notifier Script
        run: |
          chmod +x ./notifier.sh
          ./notifier.sh \
            "${{ github.event.client_payload.status }}" \
            "${{ github.event.client_payload.message }}" \
            "${{ github.event.client_payload.repo }}" \
            "${{ github.event.client_payload.env_name }}" \
            "${{ github.event.client_payload.actor }}" \
            "${{ github.event.client_payload.discord_webhook_url }}" \
            "${{ github.event.client_payload.slack_webhook_url }}" \
            "${{ github.event.client_payload.telegram_api_url }}" \
            "${{ github.event.client_payload.time }}" \
            "${{ github.event.client_payload.server_dns }}"
